<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/GeneralTesterBW/Schema.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://xmlns.abstract3.com/1605719165110" targetNamespace="http://xmlns.abstract3.com/1605719165110">
    <import namespace="http://www.tibco.com/schemas/GeneralTesterBW/Schema.xsd" location="../../Schemas/Error.xsd"/>
    <message name="Callback">
        <part name="Callback" type="xsd:string"/>
    </message>
    <message name="fault">
        <part name="Fault" element="ns:rootError"/>
    </message>
    <portType name="P3">
        <operation name="O3">
            <input message="tns:Callback"/>
            <output message="tns:Callback"/>
        </operation>
    </portType>
</definitions>