<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://ws-i.org/profiles/basic/1.1/xsd" xmlns:tns="http://xmlns.abstract.com/1605701777364" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://www.tibco.com/schemas/GeneralTesterBW/Schema.xsd" targetNamespace="http://xmlns.abstract.com/1605701777364">
    <import namespace="http://ws-i.org/profiles/basic/1.1/xsd"/>
    <import location="../../Schemas/Error.xsd" namespace="http://www.tibco.com/schemas/GeneralTesterBW/Schema.xsd"/>
    <message name="IP">
        <part name="Input" type="xsd:string"/>
    </message>
    <message name="OP">
        <part name="Output" type="xsd:string"/>
    </message>
    <message name="Fault">
        <part element="ns2:rootError" name="fault"/>
    </message>
    <portType name="P1">
        <operation name="O1">
            <input message="tns:IP"/>
            <output message="tns:OP"/>
        </operation>
    </portType>
</definitions>